### PR TITLE
Electronics Update, combine PSU and Arduino

### PR DESCRIPTION
**Pull request by alexschultze**
Major electronics rework, include all devices in library, include additional board (temp breakout)

### CODE REVIEW

**Comment by zisi** [comment]
Hey, i have some issues with the new boards. 
The position of switching regulator it seems to block arduino's micro usb port.
I believe that the C2 is not necessary because the ripple reduced and the LC protection is done by the capacitor that placed close to the stepper driver.
I can open the spice files with the Qucs (open source circuit simulator), what program uses to open it?

Also, i want to write about the additions you made.
The temperature sensor LM75 is a good addition because is important to know about 
the temperature of rotator, and used them as alarm when the temp is to high or to low
(extreme conditions).
The update in the end stops is important because with a normal open (when the emitter lights the photo transistor), output you can tell easier if the board has a problem or not.
In the satnogs board the additions in arduino-motor driver section are necessary (jumpers for the microstepping, status led, add headers with 5V-GND, updates in schematic and board).
For the power distribution is used a single point for each active component, that reduces the EMI.
In power section, the 5.6V zener it is necessary for protection because when the user trim the regulator at 5V it is possible to overcame and cause problems in the rest circuit. 
The capacitor C1 at 5V is used to reduce the output ripple, according to datasheet of LM2596 this can be done either with LC filter in the output or with use a large value capacitor.
The lightning protection / grounding, as i searched it seems something that is used. Also the article 
http://space.pub/2015/03/building-a-satnogs-groundstation-grounding-and-lightning-protection/ is very helpful!

**Comment by alexschultze** [comment]
Dimension:
Well yes that happened because I tried to keep it as small as possible. After 100x80 mm it is not possible to edit with the free version of Eagle (but I could not stay within this requirement anyway, this is why there is a light version). We should agree on a size for the PCB and then I can just stretch it. I think something like 140x100 would be nice as it fits an Euro casing.

Capacitors:
I was thinking the absolute opposite recently. I am horrified how the GND level on which the RTLSDR might see looks just horrible thats why I try to keep it stable close to the DC-DC also. I was thinking about adding smaller and fast ceramic capacitors close to the stepper motors in addition!
Reference: http://www.analog.com/media/en/training-seminars/tutorials/MT-101.pdf

LM2596 Ripple:
This in addition, actually there is no LC ripple filter now that you say it, only the L used for the buck converter. Maybe thats a good addition ..

Simulation:
Oops, that didnt suppose to be there. However, that can be opened with any SPICE or LTSPICE sim and was taking a look at estimated voltage ripple from stepper motor (not including ringing of course..)

**Comment by acinonyx** [comment]
Hey, Alex. I haven't reviewed the changes you made on the PCB but from the discussion they seem quite useful. I have some comments though. First of all, you have created a collection of datasheets in PDF and png format. Unfortunately, these files cannot be merged because we do not have appopriate license to redistribute them. Regarding Eagle PCB dimension limitations, I would suggest we switch to an open source CAD alternative like Kicad which has no such limitations. There is also gEDA, but it does not seem mature enough to use.

**Comment by alexschultze** [comment]
I have not considered the legal issues with datasheets. I have removed any traces of them with a force-push and pushed a new, clean and combined commit and replaced that with a Markdown document. 

KiCad probably is a reasonable idea. Currently I am not proficient on KiCad and dont know how well the conversion tools actually are.

**Comment by alexschultze** [comment]
*The PCB length is increased by 5 mm to accomodate Arduino MicroUSB

**Pull request closed without merging**
